[KOGITO-5779] - Images failing due to  no more existing (#696)
Signed-off-by: spolti <fspolti@redhat.com>

diff --git a/modules/kogito-s2i-core/added/s2i-core b/modules/kogito-s2i-core/added/s2i-core
--- a/modules/kogito-s2i-core/added/s2i-core
+++ b/modules/kogito-s2i-core/added/s2i-core
@@ -102,25 +102,29 @@ function build_kogito_app() {
             -Djacoco.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Dpmd.skip=true -Dfabric8.skip=true
 
     else
-        local ARCHETYPE_ARTIFACT_ID
-        # for product builds, the "dm" identifier will be used
-        local BUILD_IDENTIFIER="-"
-        if [[ "${JBOSS_IMAGE_NAME}" =~ "rhpam-7" ]]; then
-            BUILD_IDENTIFIER="-dm-"
-        fi
+        log_info "---> Generating $RUNTIME_TYPE project structure for $PROJECT_ARTIFACT_ID..."
         if [ "${RUNTIME_TYPE}" == "${QUARKUS_RUNTIME_TYPE}" ]; then
-            ARCHETYPE_ARTIFACT_ID="kogito-quarkus${BUILD_IDENTIFIER}archetype"
+            local quarkus_version
+            quarkus_version=$(get_quarkus_version) || exit 1
+            log_info "----> Using Quarkus version ${quarkus_version} to bootstrap the application."
+
+            $MAVEN_HOME/bin/mvn -U -B ${MAVEN_ARGS_APPEND} -s "${KOGITO_HOME}"/.m2/settings.xml \
+                io.quarkus:quarkus-maven-plugin:"${quarkus_version}":create  \
+                    -DprojectGroupId=$PROJECT_GROUP_ID \
+                    -DprojectArtifactId=$PROJECT_ARTIFACT_ID \
+                    -DprojectVersion=$PROJECT_VERSION \
+                    -Dextensions="kogito"
+
         elif [ "${RUNTIME_TYPE}" == "${SPRINGBOOT_RUNTIME_TYPE}" ]; then
-            ARCHETYPE_ARTIFACT_ID="kogito-springboot${BUILD_IDENTIFIER}archetype"
+            log_info "----> Using Spring Boot to bootstrap the application."
+            $MAVEN_HOME/bin/mvn archetype:generate -U -B -DinteractiveMode=false -DarchetypeGroupId=org.kie.kogito \
+                -DarchetypeArtifactId=kogito-spring-boot-archetype -DarchetypeVersion=$KOGITO_VERSION \
+                -DgroupId=$PROJECT_GROUP_ID -DartifactId=$PROJECT_ARTIFACT_ID -Dversion=$PROJECT_VERSION \
+                ${MAVEN_ARGS_APPEND} -s "${KOGITO_HOME}"/.m2/settings.xml
         else
             log_error "---> Invalid RUNTIME_TYPE(${RUNTIME_TYPE}) provided, failing build..."
             exit 1
         fi
-
-        log_info "---> Generating $RUNTIME_TYPE project structure using the $ARCHETYPE_ARTIFACT_ID archetype..."
-        $MAVEN_HOME/bin/mvn archetype:generate -U -B -DinteractiveMode=false -DarchetypeGroupId=org.kie.kogito -DarchetypeArtifactId=$ARCHETYPE_ARTIFACT_ID \
-            -DarchetypeVersion=$KOGITO_VERSION -DgroupId=$PROJECT_GROUP_ID -DartifactId=$PROJECT_ARTIFACT_ID -Dversion=$PROJECT_VERSION \
-            ${MAVEN_ARGS_APPEND} -s "${KOGITO_HOME}"/.m2/settings.xml
 
         # remove resources generated by the archetype
         log_info "--> Remove archetype generated resources"
@@ -139,7 +143,7 @@ function build_kogito_app() {
                 if [[ ${item} =~ .*\.sw\.(yaml|yml|json) ]]; then
                     if [[ "${RUNTIME_TYPE}" == "${QUARKUS_RUNTIME_TYPE}" ]]; then
                         log_info "--> Found Serverless Workflow file. Will add Kogito Quarkus Workflows extension to the project."
-                        require_sw=true
+                        require_sw="true"
                     else
                         log_warning "--> Builds from Serverless Workflow files are not supported for SpringBoot. Please build your project locally or use Quarkus."
                         break
@@ -152,18 +156,17 @@ function build_kogito_app() {
         mv -v $PROJECT_ARTIFACT_ID/* .
 
         # add extension if needed
-        if [ ${require_sw} = true ]; then
+        if [ "${require_sw}" == "true" ]; then
             log_info "--> Adding Kogito Quarkus Workflows extension to the generated project."
-            # we must set the evaluate version since forceStdout is not available in previous versions
-            quarkus_version=$($MAVEN_HOME/bin/mvn ${MAVEN_ARGS_APPEND} -s "${KOGITO_HOME}"/.m2/settings.xml help:evaluate -q -DforceStdout -Dexpression=quarkus.version)
-            if [[ ! "$quarkus_version" =~ [0-9]{0,2}\.[0-9]{0,3} ]]; then
-                log_error "--> Impossible to get Quarkus version from the generated Maven project (output: '$quarkus_version'), failing build"
-                exit 1
-            fi
 
+            # we must set the evaluate version since forceStdout is not available in previous versions
+            local quarkus_version
+            quarkus_version=$(get_quarkus_version) || exit 1
             log_info "--> Quarkus version is '$quarkus_version'"
 
-            $MAVEN_HOME/bin/mvn ${MAVEN_ARGS_APPEND} -s "${KOGITO_HOME}"/.m2/settings.xml io.quarkus:quarkus-maven-plugin:$quarkus_version:add-extension -Dextensions="org.kie.kogito:kogito-quarkus-serverless-workflow"
+            $MAVEN_HOME/bin/mvn ${MAVEN_ARGS_APPEND} -s "${KOGITO_HOME}"/.m2/settings.xml \
+                io.quarkus:quarkus-maven-plugin:"${quarkus_version}":add-extension \
+                -Dextensions="org.kie.kogito:kogito-quarkus-serverless-workflow"
         fi
 
         $MAVEN_HOME/bin/mvn clean package ${MAVEN_ARGS_APPEND} ${KOGITO_OPTS} ${nativeBuild} -s "${KOGITO_HOME}"/.m2/settings.xml \
@@ -216,4 +219,19 @@ function get_runtime_type() {
 
     log_info "---> Setting RUNTIME_TYPE to ${runtime_type}"
     echo "${runtime_type}"
+}
+
+
+function get_quarkus_version() {
+    log_info "Trying to retrieve Quarkus version from org.kie.kogito:kogito-build-parent:${KOGITO_VERSION}"
+    local ver=$($MAVEN_HOME/bin/mvn ${MAVEN_ARGS_APPEND} -s "${KOGITO_HOME}"/.m2/settings.xml help:evaluate -q \
+        -Dartifact=org.kie.kogito:kogito-build-parent:"${KOGITO_VERSION}" \
+        -Dexpression=version.io.quarkus \
+        -DforceStdout)
+
+    if [[ ! "$ver" =~ [0-9]{0,2}\.[0-9]{0,3} ]]; then
+        log_error "--> Impossible to get Quarkus version from the generated Maven project (output: '$ver'), failing build"
+        exit 1
+    fi
+    echo $ver
 }
