[10.0.x] kie-issues#1613: Add `CI :: License headers / check` GitHub Actions workflow (#2780)
Co-authored-by: Tiago Bento <1584568+tiagobento@users.noreply.github.com>

diff --git a/.github/workflows/ci_check_license_headers.yaml b/.github/workflows/ci_check_license_headers.yaml
--- a/.github/workflows/ci_check_license_headers.yaml
+++ b/.github/workflows/ci_check_license_headers.yaml
@@ -1,3 +1,4 @@
+#
 # Licensed to the Apache Software Foundation (ASF) under one
 # or more contributor license agreements.  See the NOTICE file
 # distributed with this work for additional information
@@ -14,25 +15,29 @@
 # KIND, either express or implied.  See the License for the
 # specific language governing permissions and limitations
 # under the License.
+#
 
-.PHONY: all
-all: test
+name: "CI :: License headers"
 
-##@ Development
+on:
+  push:
+    branches: [main]
+  pull_request:
+    branches: ["**"]
+    types: [opened, reopened, ready_for_review, synchronize]
 
-.PHONY: fmt
-fmt: ## Run go fmt against code.
-	go fmt ./...
+jobs:
+  check:
+    runs-on: ubuntu-latest
 
-.PHONY: vet
-vet: ## Run go vet against code.
-	go vet ./...
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-.PHONY: test
-test: fmt vet ## Run tests.
-	go test ./... -coverprofile cover.out
+      - name: Download Apache RAT
+        run: |
+          curl -LO https://repo1.maven.org/maven2/org/apache/rat/apache-rat/0.16.1/apache-rat-0.16.1.jar
 
-.PHONY: clean
-clean:
-	rm -rf bin/
-        
+      - name: Run Apache RAT
+        run: |
+          java -jar apache-rat-0.16.1.jar -d . -E .rat-excludes | grep "== File:" && echo "The files listed above are missing license headers." && exit 1 || echo "All files have license headers."
